### PR TITLE
Add cert-manager mixin

### PR DESCRIPTION
**Pull request by paulfantom**
As in title

/cc @benclapp

### CODE REVIEW

**Comment by benclapp** [comment]
Awesome, looks great! Thanks for kicking this off :) 

Quick question - is it common for people to add an MR here if there updates to alerts/rules/dashboards in a mixin? Happy to do as we make changes just wanting to get an idea.

**Comment by paulfantom** [comment]
> is it common for people to add an MR here if there updates to alerts/rules/dashboards in a mixin?

This repository has a [daily cronjob](https://github.com/monitoring-mixins/website/blob/master/.github/workflows/cron.yaml) which regenerates everything, so no need for manual updates.

**Comment by benclapp** [comment]
Anything I can help with to get this merged?

**Comment by paulfantom** [comment]
@benclapp I would like to get some feedback on https://gitlab.com/uneeq-oss/cert-manager-mixin/-/issues/1

**Comment by paulfantom** [comment]
cert-manager mixin is now included on the site at https://monitoring.mixins.dev/cert-manager/. Thanks @benclapp for the patience and quick fixes in the mixin :100:

**Pull request merged**
